### ISSUE TITLE
Maintainership suggestion

### ISSUE THREAD

**Issue by pataquets** [sebasmonia/tfsmacs#18]
As per your repo readme:
> NOTICE: I'm not working daily with TFVC anymore. I will continue supporting the package, but if anyone is interested in taking over or just contributing new features, feel free to do so!

I would like to suggest [Adoptoposs · Keep open source software maintained](https://adoptoposs.org/) which might be of interest for you.

**Comment by sebasmonia** [comment]
Hello,

That is a great suggestion, I will submit the package, thank you!!!

**Comment by pataquets** [comment]
@sebasmonia As soon as you post it, I'd suggest to put the relevant project link in the readme, too. Maybe also posting a new 'help wanted'/'[co]maintainers wanted' type issue might be helpful, too.

**Comment by sebasmonia** [comment]
Hi hi! it took me forever to get to this, ooops.
I submitted the project in that page!

Honestly nowadays TFVC is almost a relic of the past, at the same time, that means it could be a life saver for the one poor soul that has to interact with it from Emacs.
Wish I knew about vc-mode back when I wrote this... :)

**Comment by pataquets** [comment]
Very thoughtful of you, @sebasmonia. Thank you.
Indeed, I also think some "poor soul" might find this helpful. :smile:
I was about to submit this at https://www.reddit.com/r/emacs/comments/fqji2t/any_elisp_projects_looking_for_contributors/ , but the project is not shown as listed in Adoptoposs :thinking:. Maybe there is some sort of human review/approval.
